### ISSUE TITLE
 Make background color of light theme a bit darker (F0F0F0?)

### ISSUE THREAD

**Issue by GruetzmacherD** [rgruetz/check-assignments#6]
On my LCD display at home, it is very difficult to tell that the current background color is not white. In conjunction with this, could the horizontal rules be darkened slightly in the light theme?

**Comment by rgruetz** [comment]
I'm not thinking that we should make the background color any darker, as it might be nice for people who are working with other applications with a white background (e.g. MS Word). We could consider adding an additional gray theme as an alternative - but I think the light theme should stay light.
